### ISSUE TITLE
Telegram X Android problem

### ISSUE THREAD

**Issue by GoldenOne1** [FreedomPrevails/JSMTProxy#23]
Tnx , This really works well on Windows Server 2008
but my proxy gets error on Telegram X android

Telegram Android and Telegram Desktop are OK
Problem is Telegram X Android (new version supports mtproto)

Whats Solution?

**Comment by TitanComputer** [comment]
I've checked. problem exist. i'll add manually other ips of telegram to the codes but didn't work.

**Comment by ehaidari** [comment]
i have same problem with telegram x android.
i cant connect to jsmtproxy!
please update JSMTProxy to new version.

**Comment by masterprogrammer513** [comment]
The problem resolved in my new fork
https://github.com/masterprogrammer513/JSMTProxy

**Comment by GoldenOne1** [comment]
your fork didnt work on any client
not connected on telegram,telegram x,telegram desktop

**Comment by masterprogrammer513** [comment]
@ea1234567  There is 13 connected client online 
There is no problem in this code

**Comment by GoldenOne1** [comment]
@cinohee but im sure you forgot something
plz check codes again
tnx

**Comment by masterprogrammer513** [comment]
This is my server
My friend also run on centos7 x64 without any problem
Please check firewall and user config
![image](https://user-images.githubusercontent.com/23259226/41507383-b596c64a-7246-11e8-9ca6-4c2b72e91ddc.png)

**Comment by masterprogrammer513** [comment]
@ea1234567  check my new version file I increased timeout to 30 sec again

**Comment by GoldenOne1** [comment]
i checked again new version
not connected
can you check codes? :(
@cinohee

**Comment by GoldenOne1** [comment]
when i use FreedomPrevails/JSMTProxy all of clients are ok (except telegram x)
but when i use your fork all of clients get error
i cheked again and again (atleast 5 times) 
@cinohee 
@FreedomPrevails

**Comment by K900** [comment]
[This commit](https://github.com/cinohee/JSMTProxy/commit/751026c043670d83f62bd59d4cb07cd77d793645#diff-f1f662db08cd0a12a553239e686e428aR62) has the right idea - you just need to pass the protocol tag (either `0xef 0xef 0xef 0xef` or `0xee 0xee 0xee 0xee`) to the Telegram servers to make the proxy work.

**Comment by GoldenOne1** [comment]
@K900 can you copy past codes here?
i dont uderstand

**Comment by K900** [comment]
I'm not familiar enough with JS to rewrite the code. If you just want a working solution, try [this](https://github.com/alexbers/mtprotoproxy/pull/27) - I've implemented similar changes there and can confirm it works on multiple devices.

**Comment by GoldenOne1** [comment]
@K900 i have windows server

**Comment by K900** [comment]
The Python version of the proxy should run just fine on Windows, including my fork of it. Also, this is horribly off-topic for this repository.

**Comment by GoldenOne1** [comment]
@K900 its need docker
i have only 1 core cpu and 1gb ram

**Comment by K900** [comment]
It does not need Docker, running the script manually works just fine.

**Comment by masterprogrammer513** [comment]
@ea1234567  do you just replace new code with old one?
Could you give me remote address team viewer or etc?

**Comment by GoldenOne1** [comment]
@K900 really? its very good
do you have any manuals or guide about how run this script on windows?

**Comment by K900** [comment]
I can help you run it, but you'll have to contact me on Telegram: t.me/k900x. I'm not going to spam this unrelated issue any more.

**Comment by masterprogrammer513** [comment]
@ea1234567 do you use my config for user manager?
This code manage user to avoid multiple login with one server based on IP.
You could set unlimited or limited connection

**Comment by GoldenOne1** [comment]
@cinohee  this is my anydesk id:  461457966
anydesk is portable software like team viewer (only 2mb size)
can you connect to my pc?

**Comment by masterprogrammer513** [comment]
@ea1234567  add all file in my fork to avoid any problem
Contact me telegram 
secger.js
config.json

**Comment by TitanComputer** [comment]
can't start your version @masterprogrammer513 

on starting it hangs on loop and after few moments stops.

**Comment by masterprogrammer513** [comment]
@titancomputer
You need all of files I created 
Copy hole git

**Comment by TitanComputer** [comment]
@masterprogrammer513 i've copied the full clone of your files.

didn't start at all.

**Comment by masterprogrammer513** [comment]
@titancomputer  i found there is bug in config file there is one simicolon more.
download new config file and retest

**Comment by TitanComputer** [comment]
@masterprogrammer513 yes, what a bug!
app gets start but telegram x android didn't work with your codes too.
all other clients do OK.

**Comment by masterprogrammer513** [comment]
@titancomputer  please attention just telegeram X beta work with mtproto 
Please update to latest beta version
If use unlimite : false only ine ip could connect to server set it into true
I test with telegramX beta latest version on blue stack without any problem
and my friend test on windows mobile version of Telegram
Change secret code to new code and retest

**Comment by TitanComputer** [comment]
@masterprogrammer513 i know that, i've got last version beta of telegram x on play store, works with proxies that made with [MTProxy](https://github.com/TelegramMessenger/MTProxy) but didn't work on your codes or @FreedomPrevails 

tested many secret, make no difference.
is secret may changes anything? how we can get a OK secret?

**Comment by masterprogrammer513** [comment]
@titancomputer  I will check it tommoro again
what is your server info? 
os,cpu,vps/dedic...

**Comment by TitanComputer** [comment]
@masterprogrammer513 windows server 2012 R2, 2GB RAM, 2 Core XEON E3-1270 v6

**Comment by masterprogrammer513** [comment]
@titancomputer  what is you telegram Xmobile number country?
maybe we need add more telegram server ip to file
which proxy server workh with Telegram X?
Do you have source code of that proxy?

**Comment by TitanComputer** [comment]
@masterprogrammer513 country IR +98
[this](https://github.com/TelegramMessenger/MTProxy) mtproto is working with all.
i already asked problem on tdlib in [here](https://github.com/tdlib/td/issues/292).

**Comment by masterprogrammer513** [comment]
@titancomputer  another user told me after error 400 the connection will work after 30sec
Do you test after error 400?

**Comment by masterprogrammer513** [comment]
@titancomputer  make separated user for TelegramX and check again

**Comment by masterprogrammer513** [comment]
![image](https://user-images.githubusercontent.com/23259226/41529545-cea546b8-7302-11e8-841c-1584fb9e7a71.png)

**Comment by TitanComputer** [comment]
@masterprogrammer513 thats true. it takes too long but get connected.
very slow on updating or downloading.
i do that for 2 account. one for x one for others. no difference.

**Comment by masterprogrammer513** [comment]
@titancomputer  I think it will become faster after some texting
I will check is deference between Telegram and X version servers IP

**Comment by GoldenOne1** [comment]
@masterprogrammer513  @titancomputer  yes after 30-60 second connection established but speed is low
i think we must connect to middle east servers not europe
problem is ip address

**Comment by GoldenOne1** [comment]
@masterprogrammer513 

IP list:

proxy_for 1 149.154.175.50:8888;
proxy_for -1 149.154.175.50:8888;
proxy_for 2 149.154.162.24:80;
proxy_for 2 149.154.162.22:80;
proxy_for -2 149.154.162.24:80;
proxy_for -2 149.154.162.22:80;
proxy_for 3 149.154.175.100:8888;
proxy_for -3 149.154.175.100:8888;
proxy_for 4 91.108.4.199:8888;
proxy_for 4 91.108.4.209:8888;
proxy_for 4 91.108.4.192:8888;
proxy_for 4 91.108.4.140:8888;
proxy_for 4 91.108.4.174:8888;
proxy_for 4 91.108.4.162:8888;
proxy_for 4 91.108.4.165:8888;
proxy_for 4 91.108.4.228:8888;
proxy_for 4 91.108.4.166:8888;
proxy_for 4 91.108.4.142:8888;
proxy_for -4 149.154.165.250:8888;
proxy_for -4 149.154.165.109:8888;
proxy_for 5 91.108.56.183:8888;
proxy_for 5 91.108.56.176:8888;
proxy_for -5 91.108.56.183:8888;
proxy_for -5 91.108.56.176:8888;

**Comment by masterprogrammer513** [comment]
@titancomputer  I think this is Telegram X beta bug that not work perfectly with MTPROTO proxy .
The X version do not support all secret key.
I think better wait until released version of Telegram X

**Comment by GoldenOne1** [comment]
@masterprogrammer513

 I think so

**Comment by TitanComputer** [comment]
@ea1234567 @masterprogrammer513 
this is ok with x android. tested for 3 days.
https://t.me/proxy?server=proxy.digitalresistance.dog&port=443&secret=d41d8cd98f00b204e9800998ecf8427e

**Comment by GoldenOne1** [comment]
@titancomputer @masterprogrammer513  You are right,other proxies work well on Telegram X

**Comment by TitanComputer** [comment]
@masterprogrammer513 didn't resolve the issue?

**Comment by nullers** [comment]
@FreedomPrevails This messages comes: error (400: connection closed) on Telegram X 0.20.10.947-armeabi-v7a

**Comment by Djmahdi0098** [comment]
I'm connected but my download speed is low (Telegram , telegram X , etc)
The connection is not stable, it is permanently disconnected on some devices (telegram X)

and what is say ? 
`openssl config failed: error:02001003:system library:fopen:No such process`

**Comment by Djmahdi0098** [comment]
@masterprogrammer513

**Comment by SHAliakbari** [comment]
any progress ?! i already have problem with Telegram X android version !
